--Se inserta directamente desde el front
INSERT INTO usuarios (id, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, email, rol_id, contraseña) VALUES
('25257529-4', 'Edwin', 'Lamanna', 'Velazquez', '04-02-1989', 'elamannav@gmail.com', 2, 'pharma5+'),
('25254097-0', 'onnaive', 'Nebreda', 'Velazquez', '01-02-1987', 'onnaivenebreda@gmail.com',DEFAULT, '303030');

--Se inserta directamente desde el front, pero se insertara automaticamente como transaccion al momento de crear el usuario en el front
INSERT INTO usuario_info (id, Usuario_id, direccion, nro_calle, vivienda_id, nro_departamento, bloque_departamento, region_id, comuna_id, telefono_movil, telefono_fijo) VALUES
(DEFAULT, '25257529-4', '', '', 1, '', '', 1, 1, '', ''),
(DEFAULT, '25254097-0', '', '', 1, '', '', 1, 1, '', '');

-- despues de crear el primer usuario en el front, se debe modificar el campo rol_id para que sea 1 (administrador)
UPDATE usuarios SET rol_id = 1 WHERE id = '25257529-4';

--Se inserta directamente desde el back para que aparezca listo desde el front
INSERT INTO roles (id, rol) VALUES
 (DEFAULT, 'Administrador'),
 (DEFAULT, 'Usuario');

--Se inserta directamente desde el back para que aparezca listo desde el front
INSERT INTO vivienda (id, casa_dpto) VALUES
 (DEFAULT, 'casa'),
 (DEFAULT, 'dpto');

--Se inserta directamente desde el back para que aparezca listo desde el front
INSERT INTO regiones (id, region) VALUES
 (DEFAULT, 'Tarapacá'),
 (DEFAULT, 'Valparaíso'),
 (DEFAULT, 'Atacama'),
 (DEFAULT, 'Coquimbo'),
 (DEFAULT, 'Antofagasta'),
 (DEFAULT, 'Libertador General Bernardo O''Higgins'),
 (DEFAULT, 'Maule'),
 (DEFAULT, 'Biobío'),
 (DEFAULT, 'La Araucanía'),
 (DEFAULT, 'Los Lagos'),
 (DEFAULT, 'Aysén del General Carlos Ibáñez del Campo'),
 (DEFAULT, 'Magallanes y de la Antártica Chilena'),
 (DEFAULT, 'Metropolitana de Santiago'),
 (DEFAULT, 'Los Ríos'),
 (DEFAULT, 'Arica y Parinacota'),
 (DEFAULT, 'Ñuble');

--Se inserta directamente desde el back para que aparezca listo desde el front
INSERT INTO comunas (id, comuna, region_id) VALUES
(DEFAULT, 'Iquique', 1),
(DEFAULT, 'Alto Hospicio', 1),
(DEFAULT, 'Pozo Almonte', 1),
(DEFAULT, 'Camiña', 1),
(DEFAULT, 'Colchane', 1),
(DEFAULT, 'Huara', 1),
(DEFAULT, 'Pica', 1),
(DEFAULT, 'Antofagasta', 2),
(DEFAULT, 'Mejillones', 2),
(DEFAULT, 'Sierra Gorda', 2),
(DEFAULT, 'Taltal', 2),
(DEFAULT, 'Calama', 2),
(DEFAULT, 'Ollagüe', 2),
(DEFAULT, 'San Pedro De Atacama', 2),
(DEFAULT, 'Tocopilla', 2),
(DEFAULT, 'María Elena', 2),
(DEFAULT, 'Copiapó', 3),
(DEFAULT, 'Caldera', 3),
(DEFAULT, 'Tierra Amarilla', 3),
(DEFAULT, 'Chañaral', 3),
(DEFAULT, 'Diego De Almagro', 3),
(DEFAULT, 'Vallenar', 3),
(DEFAULT, 'Alto Del Carmen', 3),
(DEFAULT, 'Freirina', 3),
(DEFAULT, 'Huasco', 3),
(DEFAULT, 'La Serena', 4),
(DEFAULT, 'Coquimbo', 4),
(DEFAULT, 'Andacollo', 4),
(DEFAULT, 'La Higuera', 4),
(DEFAULT, 'Paihuano', 4),
(DEFAULT, 'Vicuña', 4),
(DEFAULT, 'Illapel', 4),
(DEFAULT, 'Canela', 4),
(DEFAULT, 'Los Vilos', 4),
(DEFAULT, 'Salamanca', 4),
(DEFAULT, 'Ovalle', 4),
(DEFAULT, 'Combarbalá', 4),
(DEFAULT, 'Monte Patria', 4),
(DEFAULT, 'Punitaqui', 4),
(DEFAULT, 'Río Hurtado', 4),
(DEFAULT, 'Valparaíso', 5),
(DEFAULT, 'Casablanca', 5),
(DEFAULT, 'Concón', 5),
(DEFAULT, 'Juan Fernández', 5),
(DEFAULT, 'Puchuncaví', 5),
(DEFAULT, 'Quintero', 5),
(DEFAULT, 'Viña Del Mar', 5),
(DEFAULT, 'Isla De Pascua', 5),
(DEFAULT, 'Los Andes', 5),
(DEFAULT, 'Calle Larga', 5),
(DEFAULT, 'Rinconada', 5),
(DEFAULT, 'San Esteban', 5),
(DEFAULT, 'La Ligua', 5),
(DEFAULT, 'Cabildo', 5),
(DEFAULT, 'Papudo', 5),
(DEFAULT, 'Petorca', 5),
(DEFAULT, 'Zapallar', 5),
(DEFAULT, 'Quillota', 5),
(DEFAULT, 'La Calera', 5),
(DEFAULT, 'Hijuelas', 5),
(DEFAULT, 'La Cruz', 5),
(DEFAULT, 'Nogales', 5),
(DEFAULT, 'San Antonio', 5),
(DEFAULT, 'Algarrobo', 5),
(DEFAULT, 'Cartagena', 5),
(DEFAULT, 'El Quisco', 5),
(DEFAULT, 'El Tabo', 5),
(DEFAULT, 'Santo Domingo', 5),
(DEFAULT, 'San Felipe', 5),
(DEFAULT, 'Catemu', 5),
(DEFAULT, 'Llay-Llay', 5),
(DEFAULT, 'Panquehue', 5),
(DEFAULT, 'Putaendo', 5),
(DEFAULT, 'Santa María', 5),
(DEFAULT, 'Quilpué', 5),
(DEFAULT, 'Limache', 5),
(DEFAULT, 'Olmué', 5),
(DEFAULT, 'Villa Alemana', 5),
(DEFAULT, 'Rancagua', 6),
(DEFAULT, 'Codegua', 6),
(DEFAULT, 'Coinco', 6),
(DEFAULT, 'Coltauco', 6),
(DEFAULT, 'Doñihue', 6),
(DEFAULT, 'Graneros', 6),
(DEFAULT, 'Las Cabras', 6),
(DEFAULT, 'Machalí', 6),
(DEFAULT, 'Malloa', 6),
(DEFAULT, 'Mostazal', 6),
(DEFAULT, 'Olivar', 6),
(DEFAULT, 'Peumo', 6),
(DEFAULT, 'Pichidegua', 6),
(DEFAULT, 'Quinta De Tilcoco', 6),
(DEFAULT, 'Rengo', 6),
(DEFAULT, 'Requínoa', 6),
(DEFAULT, 'San Vicente', 6),
(DEFAULT, 'Pichilemu', 6),
(DEFAULT, 'La Estrella', 6),
(DEFAULT, 'Litueche', 6),
(DEFAULT, 'Marchigüe', 6),
(DEFAULT, 'Navidad', 6),
(DEFAULT, 'Paredones', 6),
(DEFAULT, 'San Fernando', 6),
(DEFAULT, 'Chépica', 6),
(DEFAULT, 'Chimbarongo', 6),
(DEFAULT, 'Lolol', 6),
(DEFAULT, 'Nancagua', 6),
(DEFAULT, 'Palmilla', 6),
(DEFAULT, 'Peralillo', 6),
(DEFAULT, 'Placilla', 6),
(DEFAULT, 'Pumanque', 6),
(DEFAULT, 'Santa Cruz', 6),
(DEFAULT, 'Talca', 7),
(DEFAULT, 'Constitución', 7),
(DEFAULT, 'Curepto', 7),
(DEFAULT, 'Empedrado', 7),
(DEFAULT, 'Maule', 7),
(DEFAULT, 'Pelarco', 7),
(DEFAULT, 'Pencahue', 7),
(DEFAULT, 'Río Claro', 7),
(DEFAULT, 'San Clemente', 7),
(DEFAULT, 'San Rafael', 7),
(DEFAULT, 'Cauquenes', 7),
(DEFAULT, 'Chanco', 7),
(DEFAULT, 'Pelluhue', 7),
(DEFAULT, 'Curicó', 7),
(DEFAULT, 'Hualañé', 7),
(DEFAULT, 'Licantén', 7),
(DEFAULT, 'Molina', 7),
(DEFAULT, 'Rauco', 7),
(DEFAULT, 'Romeral', 7),
(DEFAULT, 'Sagrada Familia', 7),
(DEFAULT, 'Teno', 7),
(DEFAULT, 'Vichuquén', 7),
(DEFAULT, 'Linares', 7),
(DEFAULT, 'Colbún', 7),
(DEFAULT, 'Longaví', 7),
(DEFAULT, 'Parral', 7),
(DEFAULT, 'Retiro', 7),
(DEFAULT, 'San Javier', 7),
(DEFAULT, 'Villa Alegre', 7),
(DEFAULT, 'Yerbas Buenas', 7),
(DEFAULT, 'Concepción', 8),
(DEFAULT, 'Coronel', 8),
(DEFAULT, 'Chiguayante', 8),
(DEFAULT, 'Florida', 8),
(DEFAULT, 'Hualqui', 8),
(DEFAULT, 'Lota', 8),
(DEFAULT, 'Penco', 8),
(DEFAULT, 'San Pedro De La Paz', 8),
(DEFAULT, 'Santa Juana', 8),
(DEFAULT, 'Talcahuano', 8),
(DEFAULT, 'Tomé', 8),
(DEFAULT, 'Hualpén', 8),
(DEFAULT, 'Lebu', 8),
(DEFAULT, 'Arauco', 8),
(DEFAULT, 'Cañete', 8),
(DEFAULT, 'Contulmo', 8),
(DEFAULT, 'Curanilahue', 8),
(DEFAULT, 'Los Álamos', 8),
(DEFAULT, 'Tirúa', 8),
(DEFAULT, 'Los Ángeles', 8),
(DEFAULT, 'Antuco', 8),
(DEFAULT, 'Cabrero', 8),
(DEFAULT, 'Laja', 8),
(DEFAULT, 'Mulchén', 8),
(DEFAULT, 'Nacimiento', 8),
(DEFAULT, 'Negrete', 8),
(DEFAULT, 'Quilaco', 8),
(DEFAULT, 'Quilleco', 8),
(DEFAULT, 'San Rosendo', 8),
(DEFAULT, 'Santa Bárbara', 8),
(DEFAULT, 'Tucapel', 8),
(DEFAULT, 'Yumbel', 8),
(DEFAULT, 'Alto Biobío', 8),
(DEFAULT, 'Temuco', 9),
(DEFAULT, 'Carahue', 9),
(DEFAULT, 'Cunco', 9),
(DEFAULT, 'Curarrehue', 9),
(DEFAULT, 'Freire', 9),
(DEFAULT, 'Galvarino', 9),
(DEFAULT, 'Gorbea', 9),
(DEFAULT, 'Lautaro', 9),
(DEFAULT, 'Loncoche', 9),
(DEFAULT, 'Melipeuco', 9),
(DEFAULT, 'Nueva Imperial', 9),
(DEFAULT, 'Padre Las Casas', 9),
(DEFAULT, 'Perquenco', 9),
(DEFAULT, 'Pitrufquén', 9),
(DEFAULT, 'Pucón', 9),
(DEFAULT, 'Saavedra', 9),
(DEFAULT, 'Teodoro Schmidt', 9),
(DEFAULT, 'Toltén', 9),
(DEFAULT, 'Vilcún', 9),
(DEFAULT, 'Villarrica', 9),
(DEFAULT, 'Cholchol', 9),
(DEFAULT, 'Angol', 9),
(DEFAULT, 'Collipulli', 9),
(DEFAULT, 'Curacautín', 9),
(DEFAULT, 'Ercilla', 9),
(DEFAULT, 'Lonquimay', 9),
(DEFAULT, 'Los Sauces', 9),
(DEFAULT, 'Lumaco', 9),
(DEFAULT, 'Purén', 9),
(DEFAULT, 'Renaico', 9),
(DEFAULT, 'Traiguén', 9),
(DEFAULT, 'Victoria', 9),
(DEFAULT, 'Puerto Montt', 10),
(DEFAULT, 'Calbuco', 10),
(DEFAULT, 'Cochamó', 10),
(DEFAULT, 'Fresia', 10),
(DEFAULT, 'Frutillar', 10),
(DEFAULT, 'Los Muermos', 10),
(DEFAULT, 'Llanquihue', 10),
(DEFAULT, 'Maullín', 10),
(DEFAULT, 'Puerto Varas', 10),
(DEFAULT, 'Castro', 10),
(DEFAULT, 'Ancud', 10),
(DEFAULT, 'Chonchi', 10),
(DEFAULT, 'Curaco De Vélez', 10),
(DEFAULT, 'Dalcahue', 10),
(DEFAULT, 'Puqueldón', 10),
(DEFAULT, 'Queilén', 10),
(DEFAULT, 'Quellón', 10),
(DEFAULT, 'Quemchi', 10),
(DEFAULT, 'Quinchao', 10),
(DEFAULT, 'Osorno', 10),
(DEFAULT, 'Puerto Octay', 10),
(DEFAULT, 'Purranque', 10),
(DEFAULT, 'Puyehue', 10),
(DEFAULT, 'Río Negro', 10),
(DEFAULT, 'San Juan De La Costa', 10),
(DEFAULT, 'San Pablo', 10),
(DEFAULT, 'Chaitén', 10),
(DEFAULT, 'Futaleufú', 10),
(DEFAULT, 'Hualaihué', 10),
(DEFAULT, 'Palena', 10),
(DEFAULT, 'Coyhaique', 11),
(DEFAULT, 'Lago Verde', 11),
(DEFAULT, 'Aysén', 11),
(DEFAULT, 'Cisnes', 11),
(DEFAULT, 'Guaitecas', 11),
(DEFAULT, 'Cochrane', 11),
(DEFAULT, 'Ohiggins', 11),
(DEFAULT, 'Tortel', 11),
(DEFAULT, 'Chile Chico', 11),
(DEFAULT, 'Río Ibáñez', 11),
(DEFAULT, 'Punta Arenas', 12),
(DEFAULT, 'Laguna Blanca', 12),
(DEFAULT, 'Río Verde', 12),
(DEFAULT, 'San Gregorio', 12),
(DEFAULT, 'Cabo De Hornos', 12),
(DEFAULT, 'Antártica', 12),
(DEFAULT, 'Porvenir', 12),
(DEFAULT, 'Primavera', 12),
(DEFAULT, 'Timaukel', 12),
(DEFAULT, 'Natales', 12),
(DEFAULT, 'Torres Del Paine', 12),
(DEFAULT, 'Santiago', 13),
(DEFAULT, 'Cerrillos', 13),
(DEFAULT, 'Cerro Navia', 13),
(DEFAULT, 'Conchalí', 13),
(DEFAULT, 'El Bosque', 13),
(DEFAULT, 'Estación Central', 13),
(DEFAULT, 'Huechuraba', 13),
(DEFAULT, 'Independencia', 13),
(DEFAULT, 'La Cisterna', 13),
(DEFAULT, 'La Florida', 13),
(DEFAULT, 'La Granja', 13),
(DEFAULT, 'La Pintana', 13),
(DEFAULT, 'La Reina', 13),
(DEFAULT, 'Las Condes', 13),
(DEFAULT, 'Lo Barnechea', 13),
(DEFAULT, 'Lo Espejo', 13),
(DEFAULT, 'Lo Prado', 13),
(DEFAULT, 'Macul', 13),
(DEFAULT, 'Maipú', 13),
(DEFAULT, 'Ñuñoa', 13),
(DEFAULT, 'Pedro Aguirre Cerda', 13),
(DEFAULT, 'Peñalolén', 13),
(DEFAULT, 'Providencia', 13),
(DEFAULT, 'Pudahuel', 13),
(DEFAULT, 'Quilicura', 13),
(DEFAULT, 'Quinta Normal', 13),
(DEFAULT, 'Recoleta', 13),
(DEFAULT, 'Renca', 13),
(DEFAULT, 'San Joaquín', 13),
(DEFAULT, 'San Miguel', 13),
(DEFAULT, 'San Ramón', 13),
(DEFAULT, 'Vitacura', 13),
(DEFAULT, 'Puente Alto', 13),
(DEFAULT, 'Pirque', 13),
(DEFAULT, 'San José De Maipo', 13),
(DEFAULT, 'Colina', 13),
(DEFAULT, 'Lampa', 13),
(DEFAULT, 'Til Til', 13),
(DEFAULT, 'San Bernardo', 13),
(DEFAULT, 'Buin', 13),
(DEFAULT, 'Calera De Tango', 13),
(DEFAULT, 'Paine', 13),
(DEFAULT, 'Melipilla', 13),
(DEFAULT, 'Alhué', 13),
(DEFAULT, 'Curacaví', 13),
(DEFAULT, 'María Pinto', 13),
(DEFAULT, 'San Pedro', 13),
(DEFAULT, 'Talagante', 13),
(DEFAULT, 'El Monte', 13),
(DEFAULT, 'Isla De Maipo', 13),
(DEFAULT, 'Padre Hurtado', 13),
(DEFAULT, 'Peñaflor', 13),
(DEFAULT, 'Valdivia', 14),
(DEFAULT, 'Corral', 14),
(DEFAULT, 'Lanco', 14),
(DEFAULT, 'Los Lagos', 14),
(DEFAULT, 'Máfil', 14),
(DEFAULT, 'Mariquina', 14),
(DEFAULT, 'Paillaco', 14),
(DEFAULT, 'Panguipulli', 14),
(DEFAULT, 'La Unión', 14),
(DEFAULT, 'Futrono', 14),
(DEFAULT, 'Lago Ranco', 14),
(DEFAULT, 'Río Bueno', 14),
(DEFAULT, 'Arica', 15),
(DEFAULT, 'Camarones', 15),
(DEFAULT, 'Putre', 15),
(DEFAULT, 'General Lagos', 15),
(DEFAULT, 'Chillán', 16),
(DEFAULT, 'Bulnes', 16),
(DEFAULT, 'Chillán Viejo', 16),
(DEFAULT, 'El Carmen', 16),
(DEFAULT, 'Pemuco', 16),
(DEFAULT, 'Pinto', 16),
(DEFAULT, 'Quillón', 16),
(DEFAULT, 'San Ignacio', 16),
(DEFAULT, 'Yungay', 16),
(DEFAULT, 'Quirihue', 16),
(DEFAULT, 'Cobquecura', 16),
(DEFAULT, 'Coelemu', 16),
(DEFAULT, 'Ninhue', 16),
(DEFAULT, 'Portezuelo', 16),
(DEFAULT, 'Ránquil', 16),
(DEFAULT, 'Treguaco', 16),
(DEFAULT, 'San Carlos', 16),
(DEFAULT, 'Coihueco', 16),
(DEFAULT, 'Ñiquén', 16),
(DEFAULT, 'San Fabián', 16),
(DEFAULT, 'San Nicolás', 16);

--Se inserta directamente desde el back para que aparezca listo desde el front
INSERT INTO tipo_de_persona (id, tipo_de_persona) VALUES
(DEFAULT, 'Mujer'),
(DEFAULT, 'Niña');

--Se inserta directamente desde el back para que aparezca listo desde el front
INSERT INTO tallas (id, talla) VALUES
(DEFAULT, '4'),
(DEFAULT, '6'),
(DEFAULT, '8'),
(DEFAULT, '10'),
(DEFAULT, '12'),
(DEFAULT, '14'),
(DEFAULT, '16'),
(DEFAULT, 'XS'),
(DEFAULT, 'S'),
(DEFAULT, 'M'),
(DEFAULT, 'L'),
(DEFAULT, 'XL'),
(DEFAULT, 'XXL');

--Se inserta directamente desde el front al crear un producto
INSERT INTO productos (id, nombre, descripcion, tipo_de_persona_id, talla_id, precio_unitario) VALUES
('S1013025', 'Producto 1', 'Descripción del producto 1', 1, 10, 14990),
('S1024061', 'Producto 2', 'Descripción del producto Niña', 2, 2, 9990);